### ISSUE TITLE
Instrument ShakerParticle.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#103]
This issue was added to ShakerParticles by @samreid:

> TODO: To fully support save/load, we must also capture the particle velocities, solute type, orientation, etc.

For the benefit of whoever has to address this in the future... Please describe what would be involved, whether someone is currently working on this (I have the feeling the answer is yes, but in beaker), etc.  Thanks.

**Comment by samreid** [comment]
The basic idea is to save every part of the model state so that the simulation can be loaded from any state into any other state.

Currently, we are making the simplifying assumption that the simulation states are played back in order--this means that just playing back the positions is sufficient to replicate playback.  However, things would be physically inaccurate for "load to pick up where I left off".

I'm not working on together at the moment, so unassigning for now.  Others feel free to work on this, or I can take another look once we get back into it.

**Comment by samreid** [comment]
This does not need to be completed for S2015R.

**Comment by pixelzoom** [comment]
Since beers-law-lab has now been fully instrumented, presumably it's time to revisit this.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/beers-law-lab/issues/99

**Comment by samreid** [comment]
I instrumented ShakerParticle above, and it is working nicely in the state playback.  @pixelzoom can you review the changes to the beers-law-lab repo?  In the phet-io repo, I'm aware of some duplication of state keys that I don't plan to address now.  I'm more interested in your help double checking that the sim changes look correct.

**Comment by samreid** [comment]
Things are broken, please hold...

**Comment by samreid** [comment]
Fixed in https://github.com/phetsims/phet-io/commit/60ecf45b00d40d02c2ccb12383279c90f1b239d8 and working normally.

**Comment by pixelzoom** [comment]
Sim changes look good, minor fix to one visibility annotation.

Added TODO to this comment in beers-law-lab-api.js:
```js
115 //TODO grouped item, should have value set with create.  What is this for?  I don't know.
```

Are the TODO items in beers-law-lab-api.js being tracked somewhere in GitHub?

**Comment by samreid** [comment]
> Are the TODO items in beers-law-lab-api.js being tracked somewhere in GitHub?

https://github.com/phetsims/phet-io/issues/44 "There are 37 TODOs in the code"
