### ISSUE TITLE
apply layer-fitting hint to improve performance

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#113]
Factored this out of #112.

Take adavantage of a new scenery feature (https://github.com/phetsims/scenery/issues/406) to improve performance. @jonathanolson will provide guidance on where/how to apply this feature.

**Comment by pixelzoom** [comment]
@ariel-phet Do you want this addressed for S2015R?  If so, @jonathanolson will need to advise.

**Comment by pixelzoom** [comment]
... and perhaps @jonathanolson can comment on whether he thinks this needs to be done for S2015R. I am not aware of any reported performance issues.

**Comment by jonathanolson** [comment]
If there aren't performance complaints, I wouldn't call it a blocking issue.

**Comment by ariel-phet** [comment]
@pixelzoom - your call frankly, as long as the "dramatic drop in performance" is no longer present, previous performance was completely fine.

**Comment by pixelzoom** [comment]
Since there are no performance issues with this sim, I see no point in doing this (for S2105R or otherwise). 

Closing.

**Comment by jonathanolson** [comment]
Agreed, no plan to do this for S2015R. I'll plan to do this when https://github.com/phetsims/scenery/issues/406 is completed.

**Comment by jonathanolson** [comment]
Applied optimization and tested to make sure fitted blocks weren't resizing (with the new ?showFittedBlockBounds query parameter). Closing.

**Comment by pixelzoom** [comment]
@jonathanolson Could you please describe how a developer would go about deciding whether to add option `preventFit:true`?  I see this documentation in Node.js:

```js
      // {boolean} - If true, Scenery will not fit any blocks that contain drawables attached to Nodes underneath this
      //             node's subtree. This will typically prevent Scenery from triggering bounds computation for this
      //             sub-tree, and movement of this node or its descendants will never trigger the refitting of a block.
      preventFit: false
```

But (in the case of beers-law-lab) I have no idea why you selected ShakerNode for optimization, but not other movable nodes (eg, dropper, probes,... ) or things that animate (eg, particles that come out of shaker).  

Note that this may be a good topic for developer meeting, since I'm sure it will interest @samreid @jbphet @jessegreenberg and @arnabp.

**Comment by pixelzoom** [comment]
Playing around with beers-law-lab and `?showFittedBlockBounds`... I realize that I also don't understand what I'm seeing when this query parameters is added.  And that's probably because I don't understand what a "fitted block" is.  I suspect that I am not alone.

**Comment by jonathanolson** [comment]
Blocks are basically DOM/SVG/Canvas/WebGL layers.

Some blocks have the ability to, instead of taking up the full screen, be fitted closer to the bounds of their contents. Currently WebGL is set to always take up the full screen, but Canvas/SVG will try to fit to size to minimize memory usage (and if it doesn't change size every frame, potentially speed up things).

?showFittedBlockBounds displays the current locations of each FittedBlock (WebGL/Canvas/SVG) with a red outline. If the bounds of one of these is changing every frame during some operation (e.g. dragging the shaker), it saps performance by resizing.

The preventFit flag forces any FittedBlock that would contain the node's bounds (or a component of it) to take up the full screen if possible. This:
1. Prevents the actual SVG/Canvas element from being resized during runtime, increasing performance (Chrome was particularly bad, doing a lot of stuff for CSS layout).
2. Prevents Scenery from triggering bounds computation for this particular need. If bounds aren't computed for something else (e.g. listeners, pickability, centerX, etc.), then bounds computation on entire animated subtrees can potentially be skipped.

I'll be happy to discuss at the developer meeting more, and make any clarifications as it's a fairly advanced performance flag.

**Comment by pixelzoom** [comment]
Thanks, that's helpful.  I'll leave labeled "developer-meeting" so that other developers can ask any questions at the next meeting.

**Comment by pixelzoom** [comment]
Discussed at 12/10/15 developer meeting.  Closing.
