### ISSUE TITLE
weirdness with version numbering

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#153]
I need to deploy a dev version of beers-law-lab for verification of #148, #149, #150.  But I've run into some weirdness with the version numbering.

In @https://github.com/phetsims/beers-law-lab/commit/717fe8d7f4eb75868aa5db38bac48a849f692d7e, @samreid  incremented the version if to 1.4.0-dev.2.  But I see no 1.4.0-dev.1 or 1.4.0-dev.2 on spot in dev/html/.  What is going on here?

**Comment by samreid** [comment]
In https://github.com/phetsims/together/issues/309 I was asked to publish an instrumented beer's law lab for Ido.  I have published this in the restricted hashes directory.

In https://github.com/phetsims/together/issues/260 I have been working on publishing the first version of the phet-io site.  To do this, I must publish the interoperable simulations, including beers-law-lab, color-vision, concentration, faradays-law and molecules-and-light and hence I updated the version numbers for the publication of this new instrumented version.

The chipper issue https://github.com/phetsims/chipper/issues/270 describes how the phet-io version numbers are derived from the standard version names, and how the versions increment at the same time (rather than having one line of dev sims and a separate line of instrumented sims).

If your goal is to avoid any numbering gaps in the dev versions, I see a couple of solutions:
1. Every time the version number is incremented for publication of an instrumented sim, also publish a non-instrumented dev version.
2. Split the numberings into two lines, a separate numbering scheme for instrumented and separate for dev.

With the processes we have set up, gaps will appear in the dev versions.  Let's discuss the two related issues: (a) how to prevent gaps in the versions of future releases (if we decide to avoid gaps) and (b) how to patch the gaps for beers-law-lab for these 2 dev versions (if we decide to avoid gaps).

**Comment by samreid** [comment]
If you want to proceed immediately with 1.4.0-dev.1 you can reset the version to that for this dev version and I will work around it when publishing the next interoperable versions.  In fact, I'll do so right now so there is no bottleneck for your work.  Feel free to do the same for concentration, if you are also publishing it.

**Comment by samreid** [comment]
In the above commit, I dropped the dev version number by 1, to `1.4.0-dev.1` so that this cannot bottleneck your work, and we can discuss at our convenience.

**Comment by pixelzoom** [comment]
My goal is to make sure that I pick a version identified that doesn't collide with something that's already been published.  If I can look in spot:dev/html/ to determine whether a version id has already been used, then it's not clear how I can prevent collisions. 

The problem here is this awful hack that was added to `getBuildConfig`:

```js
  // TODO: chipper#270 workaround, part 1 (see part 2 in getBuildConfig.js)
  if ( buildConfig.brand === 'phet-io' && buildConfig.version.indexOf( '-dev' ) > -1 ) {
    buildConfig.version = buildConfig.version.replace( '-dev', '-phet-io' );
  }
```

This hack was consolidated to 2 "parts" in https://github.com/phetsims/chipper/issues/270. Perhaps we can remove this hack, now that the "phet-io" suffix is being added to html files for PhET-io branded deploys?

**Comment by pixelzoom** [comment]
My goal is to make sure that I pick a version identified that doesn't collide with something that's already been published.  If I can look in spot:dev/html/ to determine whether a version id has already been used, then it's not clear how I can prevent collisions. 

The problem here is this awful "2 part" hack that was added to getBuildConfig.js:

```js
  // TODO: chipper#270 workaround, part 1 (see part 2 in createHTMLFilename.js)
  if ( buildConfig.brand === 'phet-io' && buildConfig.version.indexOf( '-dev' ) > -1 ) {
    buildConfig.version = buildConfig.version.replace( '-dev', '-phet-io' );
  }
```

and createHTMLFilename.js:

```js
    // TODO: chipper#270 workaround, part 2 (see part 1 in getBuildConfig.js)
    if ( buildConfig.brand === 'phet-io' ) {
      var devVersion = buildConfig.version.replace( '-phet-io', '-dev' );
      string = string.replace( devVersion, buildConfig.version );
    }
```

Perhaps we can remove this hack, now that the "phet-io" suffix is being added to html files for PhET-io branded deploys?

**Comment by samreid** [comment]
I'm not too clear on the motivation for https://github.com/phetsims/chipper/issues/270, so perhaps it would be good to discuss.  You can publish BLL now with `1.4.0-dev.1` without any risk of dev versions colliding or being confused with something already published.

**Comment by samreid** [comment]
> Perhaps we can remove this hack, now that the "phet-io" suffix is being added to html files for PhET-io branded deploys?

It seems like one valuable part of https://github.com/phetsims/chipper/issues/270 was that you can open the sim and see that it reports itself as a phet-io version in the version.  But perhaps this is already accomplished by having the "phet-io" brand baked in?

**Comment by pixelzoom** [comment]
If I recall correctly, the hack in  phetsims/chipper#270 was added by @jbphet for beaker. So we should pull him into this.

**Comment by samreid** [comment]
I think I was involved too, but my memory is fuzzy.  I think the reasons we changed the suffix for publishing were primarily (a) so that interoperable versions could be published and identified on spot and (b) so that you could tell if a sim was instrumented or not by the version number within the sim.

Regarding (a), we are no longer planning to publish interoperable versions on spot.  Regarding (b) we have the brand baked in, so it is easy to see whether a sim is phet-io or not now.

Perhaps the primary outstanding issue is how to deal with version numbers for publishing interoperable versions to figaro vs the spot dev version numbers.

**Comment by samreid** [comment]
Meeting consensus: if it is a dev version of a phet-io simulation, don't replace the "dev" with "phet-io".

SR: This could leave gaps in the version numbers.

@pixelzoom: we could append the brand to the version identifier, like: 1.0.3-dev-phet-io.1

@jonathanolson: perhaps we should keep the versions matched, and deploy a production version when we deploy the phet-io version.

This means if we want to publish a phet-io production version, then the main version would need to be fully tested, and users would get a notification that there is a new version (even if there are no new features for CC-by sims).

**Comment by samreid** [comment]
Perhaps making spot "dev" password protected and creating a sibling directory "dev-public" and making it public.

**Comment by samreid** [comment]
Latest thoughts: dev/html/phet-io could be a password protected directory that is published to at the same time as the main dev version.

@jonathanolson says don't create a separate directory, just use .htaccess to make restrict access to those.

**Comment by samreid** [comment]
@pixelzoom said look into FILESMATCH.

**Comment by pixelzoom** [comment]
It's `<FilesMatch>` in .htpassword

**Comment by samreid** [comment]
@pixelzoom did I summarize the outstanding work correctly in https://github.com/phetsims/together/issues/331 ?  Can this issue be closed?

**Comment by pixelzoom** [comment]
The weirdness with the version numbering is due to the lack of a process for deploying PhET-iO dev versions.  That general issue is now being tracked in https://github.com/phetsims/chipper/issues/440. Closing.

**Comment by samreid** [comment]
FYI I'm going to bump concentration back to 1.3.0-dev.1 for a dev deploy, the other dev versions are not going to be published.

**Comment by samreid** [comment]
Done above.
