### ISSUE TITLE
cuvette width dragEnd triggers model changes

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#155]
From @phetsims/sarah-perez:

> Also, I found it counter-intuitive that when the width of the beaker is changed with the slider, the "end drag" event is followed by a "absorption detector value change" event however when the concentration is altered with the slider the reverse occurs: the "end drag" event follows the "absorption detector value change". Wouldn't it make more sense to consistently follow changes in the system with a "detector value change" event?

I replicated the behavior.  In my opinion, the correct behavior would be for there to be no further model changes upon release of the beaker width drag. @pixelzoom any idea what is causing this or if it would be easy to change?

**Comment by pixelzoom** [comment]
@ariel-phet instructed me to spend some time investigating this.

**Comment by pixelzoom** [comment]
Since the beaker width isn't variable in this sim, I'm guessing that we're talking about the cuvette, and beersLawScreen.model.cuvette.widthProperty in the API file.   Changing the issue title to reflect this.

**Comment by pixelzoom** [comment]
The relative code is in CuvetteNode.js, lines 148-153. When a drag cycle is completed, the cuvette snaps to the closest 0.1 cm interval.  This is as specified in the design document.  If the width is already on a 0.1 cm interval, then the call to `cuvette.widthProperty.set( newWidth )` is a no-op.  So a model change is expected when the drag cycle is completed. 

Back to @samreid.

**Comment by samreid** [comment]
@phetsims/sarah-perez can you review @pixelzoom's notes in the preceding comment and let me know your thoughts?

**Comment by pixelzoom** [comment]
One more note...  The cuvette width snaps to 0.1 cm intervals to facilitate measurement of the cuvette with the ruler, which is marked with 0.1 cm ticks.  Without the "snap to width" feature, the students can't accurately measure the cuvette, and therefore can't perform other necessary calculations.  So I suspect that removing the "snap" feature is unlikely to happen.

**Comment by sperez8** [comment]
I am confused... what's the difference between the beaker and cuvette?



*Sarah Perez, M.Sc*
Dynamic Assessment Research Coordinator
Centre for Teaching, Learning and Technology at UBC
www.spzfolio.com
604-842-6751

**Comment by pixelzoom** [comment]
A beaker is a vessel for experiments involving liquids, like the one in the "Concentration" screen. A cuvette is a vessel for spectroscopic experiments, like the one in the "Beer's Law" screen.  And in this sim, they are different elements in the PhET-iO data stream, so I wanted to verify that you were indeed referring to the cuvette.

**Comment by sperez8** [comment]
In that case yes I was referring to the cuvette. Just making sure there
wasn't also a beaker in addition to the cuvette in Beer's law!



*Sarah Perez, M.Sc*
Dynamic Assessment Research Coordinator
Centre for Teaching, Learning and Technology at UBC
www.spzfolio.com
604-842-6751

**Comment by pixelzoom** [comment]
And @samreid has requested your response to my diagnosis in https://github.com/phetsims/beers-law-lab/issues/155#issuecomment-178215230.

**Comment by pixelzoom** [comment]
> Just making sure there wasn't also a beaker in addition to the cuvette in Beer's law!

Beer's Law Lab does indeed have both a beaker (1st screen) and a cuvette (2nd screen).

**Comment by sperez8** [comment]
>  Without the "snap" feature, the students can't accurately measure the cuvette, and therefore can't perform other necessary calculations. So I suspect that removing the "snap" feature is unlikely to happen.

Makes sense.

> If the width is already on a 0.1 cm interval, then the call to cuvette.widthProperty.set( newWidth ) is a no-op. So a model change is expected (but not guaranteed) when the drag cycle is completed.

My main worry here is consistency for the purposes of parsing the log files. There are two consistency problems:
1. The order in which logging occurs (variable change then detector value change, or vice versa) should be consistent across events. This is more for simplicity in parsing the file but can be worked around though preferably not.

2.The fact that a model change is not guaranteed (and thus, if I understand correctly, "detector value change" won't be consistently outputted) will cause problems down the line.

It's hard for me to comment on how to change the implementation without getting deep into the code but I would naively suggest to set it up such that a "detector current value" is outputted after a drag event regardless of the snap-on feature. Does that make sense?

**Comment by pixelzoom** [comment]
> 2.The fact that a model change is not guaranteed (and thus, if I understand correctly, "detector value change" won't be consistently outputted) will cause problems down the line.

This is true of *any* TProperty value that you may be observing in the data stream. If it doesn't change, there will be no message indicating it's value.  So while we could probably add a "current value" message in the endDrag for this specific case, that's not a general solution.  If you're not designing your analysis to always expect model values in specific orders, you will have problems. 

I don't know the the specifics of your study, or how you're trying to use the data... But in this case, I would think that you would want to detect whether there is or is not a model change i the endDrag.  If there's a model change, then it means the last value change you saw was the result of the sim "snapping" the value to an increment, and was not a value set explicitly by user.  If there's no model change in the endDrag, then the last value change you saw was set by the user.

**Comment by sperez8** [comment]
I don't think I explained myself well. I agree, we're not interested in
knowing current values, only change in values.

When I write the script that will parse the log file, I need to know when I
should look for a "detector value change": is it going to be before or
after the cuvette width dragend event? My interpretation is that because of
the "snap to value" feature it's not going to be consistently after the
event. I guess there are two solutions to this:

1. logging the value of the detector after a dragend event regardless of
wither its a wavelength, concentration or beaker drag end, that way I can
consistently parse it.
2. while parsing, capturing detector change events before and after a
dragend event and if there is a detector value change after the dragend
event keeping that value as the current detector value. Is this what you
were suggesting?

Sarah



Maybe



*Sarah Perez, M.Sc*
Dynamic Assessment Research Coordinator
Centre for Teaching, Learning and Technology at UBC
www.spzfolio.com
604-842-6751

**Comment by samreid** [comment]
@sperez8 could you try appending the query parameter &emitStates to the URL?  This will make the simulation emit states every 10 seconds and deltas every frame.  I am wondering if this can help with you detecting the changes in values?

**Comment by pixelzoom** [comment]
> When I write the script that will parse the log file, I need to know when I should look for a "detector value change": is it going to be before or after the cuvette width dragend event? My interpretation is that because of the "snap to value" feature it's not going to be consistently after the event.

When the cuvette "snaps" to a width, the "widthProperty changed" event does not appear after the "dragEnded" event.  It is a child of the "dragEnded" event.  

Here's are some examples from the console when running with query parameters `?togetherEvents.log=console&phet-io-standalone`.

First, here's an example where the cuvette snapped to a 0.1 cm increment at the end of a drag. Note that the "widthProperty changed" event is a child of this event, indicating that it occurred during the dragEnd. 

```js
{
  "messageIndex": 20,
  "eventType": "user",
  "togetherID": "beersLawLab.beersLawScreen.view.cuvetteNode.cuvetteDragHandler",
  "componentType": "TTandemDragHandler",
  "event": "dragEnded",
  "time": 1454441480165,
  "parameters": {
    "x": 710,
    "y": 651
  },
  "children": [
    {
      "messageIndex": 21,
      "eventType": "model",
      "togetherID": "beersLawLab.beersLawScreen.model.cuvette.widthProperty",
      "componentType": "TProperty(TNumber)",
      "event": "changed",
      "time": 1454441480166,
      "parameters": {
        "oldValue": 1.248,
        "newValue": 1.2000000000000002
      }
    }
  ]
}
```

Next, here's an example where the user dragged the beaker to its maximum width of 2.0 cm. Since this width is an integer multiple of 0.1 cm, no "snap" occurs, so there is no "widthProperty changed" event.

```js
{
  "messageIndex": 98,
  "eventType": "user",
  "togetherID": "beersLawLab.beersLawScreen.view.cuvetteNode.cuvetteDragHandler",
  "componentType": "TTandemDragHandler",
  "event": "dragEnded",
  "time": 1454441681057,
  "parameters": {
    "x": 1263,
    "y": 667
  }
}
```

You should be writing your analysis code such that "widthProperty changed" is an optional message that may accompany "dragEnded" for the cuvette.  If you see that event, you know that the cuvette's width was adjusted by the application (not the user) after the drag ended.

**Comment by pixelzoom** [comment]
@sperez8 Since you mention "parsing" the data stream and things being "before" or "after" other things, I wanted to check on how you're parsing.

The PhET-iO data stream cannot be treated as text strings with a deterministic ordering of fields. The data stream is in JSON format, and the order of fields between any pair of curly braces is *not guaranteed* to be the same across browsers or operating systems.  

For example, on one system you may see this:

```js
{
  "messageIndex": 98,
  "eventType": "user",
  "togetherID": "beersLawLab.beersLawScreen.view.cuvetteNode.cuvetteDragHandler",
  "componentType": "TTandemDragHandler",
  "event": "dragEnded",
  "time": 1454441681057,
  "parameters": {
    "x": 1263,
    "y": 667
  }
}
```

On another systems you may see this:

```js
{
  "componentType": "TTandemDragHandler",
  "messageIndex": 98,
  "event": "dragEnded",
  "eventType": "user",
  "togetherID": "beersLawLab.beersLawScreen.view.cuvetteNode.cuvetteDragHandler",
  "parameters": {
    "x": 1263,
    "y": 667
  },
  "time": 1454441681057
}
```

These message are identical, and (because they are JSON) we have no control over the ordering of the fields.  If you are writing analysis code that treats these as text strings, you will run into problems. You need to convert the messages to JSON, then process them as JSON.

**Comment by samreid** [comment]
It seems like no more implementation work is required for this issue, just concluding discussion regarding how the log messages work.  I'll unassign it from myself and this issue can be closed when the conversation concludes.

**Comment by pixelzoom** [comment]
I'll assign this to me to wrap up the discussion.

**Comment by sperez8** [comment]
My intentions were indeed to process the messages as JSON so that the order of items within curly brackets doesn't matter. 
By "order" I meant the sequence of events by time stamp.

I think I need to play with it a bit more and get back to you on wither it will be simple/possible to parse as is.

**Comment by pixelzoom** [comment]
Great, sounds like you're proceeding in the right direction.  Let me know if you have any further questions about how to handle parsing in this particular situation.

**Comment by pixelzoom** [comment]
@sperez8 Is there anything else that needs to be done for this issue, or can it be closed?

**Comment by sperez8** [comment]
Reading over the discussion again, I realize I have all the info I need to create the parser. Now all I need is data... ;)
Thanks!

**Comment by samreid** [comment]
> Reading over the discussion again, I realize I have all the info I need to create the parser. Now all I need is data... ;)

@sperez8 do you have a link to a version of the simulation that outputs data?  You could generate your own data sets and work on the parser before collecting the student data.
