### ISSUE TITLE
method of specifying T type

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#184]
Related to code review of #181.

The most prevalent change made throughout #181 was to add a `type` option value, which indicates the type of a Property value.  For example, the bits relevant to PhET-iO in ATDetector were changed from:

```js
40 tandem: tandem.createTandem( 'modeProperty' ),
```

to:

```js
40 tandem: tandem.createTandem( 'modeProperty' ),
41 type: TString
```

And from:

```js
66 tandem: tandem.createTandem( 'valueProperty' ),
```

to:

```js
71 tandem: tandem.createTandem( 'valueProperty' ),
72 type: TNumber && TNumber( 'unitless' )
```

This makes me wonder...  Instead of adding this additional `type` option, did you consider adding a `type` parameter to `Tandem.createTandem`?

For example:

```js
 tandem: tandem.createTandem( 'valueProperty', TNumber  && TNumber( 'unitless' )  ),
```

**Comment by pixelzoom** [comment]
Specifying the T type in `createInstance` might also provide some opportunity for type checking in `addInstance`.

**Comment by samreid** [comment]
> Specifying the T type in `createInstance` might also provide some opportunity for type checking in `addInstance`.  

Did you mean `createTandem`?

**Comment by pixelzoom** [comment]
Yes, `createTandem`.

**Comment by pixelzoom** [comment]
... and if T type was specified in `createTandem`, then perhaps it wouldn't need to be also specified in `addInstance`.

**Comment by samreid** [comment]
Tagging high priority so it will show up on my radar (since this issue is not in phet-io repo).

**Comment by samreid** [comment]
Specifying the type and tandem together seems natural because the entire point of tandem is to maintain a registry of all of the phet-io instances and their types.

However, I fear this would lead to a great deal of duplication in how the types are specified.  For instance, if I am creating 4 nodes, the code may look something like this:

```js
    var node1 = new MyNode( tandem.createTandem( 'node1', TMyNode ) );
    var node2 = new MyNode( tandem.createTandem( 'node2', TMyNode ) );
    var node3 = new MyNode( tandem.createTandem( 'node3', TMyNode ) );
    var node4 = new MyNode( tandem.createTandem( 'node4', TMyNode ) );
```

In fact, after TandemNode was introduced, it felt like a good step forward because only a tandem (without type) needed to be supplied.

In this case, it seems like TMyNode is duplicated unnecessarily, and would be nice to factor that out.  On the other hand, there is a bit of symmetry in these lines because the 'node1' mirrors the var name and 'TMyNode' mirrors the constructor name.

Also, there are some cases where the tandem is not associated with an instance, but rather an intermediate node in a tree.  For instance, if there was a composite model element which did not provide its own logic or metadata but just served as a container for other model elements, it would not necessarily need to be instrumented.  In this case, the tandem's type should be omitted.  (Or we could disallow this, and say every tandem must have a type--there are no intermediate tandems).

On the other hand, specifying the type in the tandem may circumvent the problem identified in https://github.com/phetsims/phet-io/issues/532 in which subclassing an instrumented instance makes it impossible to specify a different instrumentation T type.

Still thinking this through, but wanted to write down some initial impressions.

**Comment by pixelzoom** [comment]
If you're worried about duplication, then that seems like an additional argument for specifying the T type once in the `createTandem` call, rather than in every `addInstance` call for the tandem.

**Comment by pixelzoom** [comment]
On the other hand... Are tandems intended to be homogenous? (Thinking ahead to a collection of heterogeneous objects.) If not, then perhaps the tandem should know nothing about the T type, and the T type should be associated with each instance added to the tandem.  That would argue for leaving the T type arg in `addInstance`.

**Comment by samreid** [comment]
> If you're worried about duplication, then that seems like an additional argument for specifying the T type once in the `createTandem` call, rather than in every `addInstance` call for the tandem.

I'm not understanding your thinking here.  In the code block in https://github.com/phetsims/beers-law-lab/issues/184#issuecomment-235480445 the type `TMyNode` must be specified 4 times, whereas if it was specified in the MyNode constructor at the addInstance site, it would only appear once.

**Comment by samreid** [comment]
> On the other hand... Are tandems intended to be homogenous?

The relationship is: each instrumented instance has exactly one tandem and exactly one type.  I'm not sure it would be necessary to specify the type of TObservableArray(x), though that is what is currently done.

**Comment by samreid** [comment]
As @andrewadare and I discussed in https://github.com/phetsims/phet-io/issues/532 it makes sense to progressively refine the instrumentation type at each level in the inheritance hierarchy so that order-dependent actions will still work properly (for a customized startup).  From this perspective, it makes sense for the Type to call its own tandem.addInstance(this,TType).

**Comment by pixelzoom** [comment]
OK, makes sense.

**Comment by samreid** [comment]
@pixelzoom anything else to do here?
