### ISSUE TITLE
Ruler movement is not true on extra small and extra large resolutions

### ISSUE THREAD

**Issue by zepumph** [phetsims/beers-law-lab#197]
@samreid and I noticed this while working on phet-io with BLL in an Iframe, but I noticed that it is also able to be replicated on large screen resolutions. This problem is not on the published version of the sim on phet.colorado.edu though. @pixelzoom do you have any ideas?

![bll-ruler](https://cloud.githubusercontent.com/assets/6856943/21860130/838ef078-d7ec-11e6-925c-9bef68ebcfb5.gif)

**Comment by pixelzoom** [comment]
I'll have a look. @ariel-phet priority?

**Comment by samreid** [comment]
This is also happening for the Gravity Force Lab ruler.  This problem is not isolated to beers-law-lab.  I'm not sure if it is a ruler problem (scenery-phet) or a drag handler problem (scenery).

**Comment by samreid** [comment]
My recommendation for priority: before any master deploys are done with buggy code :)

**Comment by pixelzoom** [comment]
The ruler in beers-law-lab is BLLRulerNode.  It uses `MovableDragHandler`, which extends `TandemSimpleDragHandler`, which extends `SimpleDragHandler`.   There have been a very small number of commits on MovableDragHandler and SimpleDragHandler in the recent past, so perhaps inspect those first.  But given this type hierarchy, the fact that `TandemSimpleDragHandler` was added relatively recently, I'd put my money on this being a problem introduced by PhET-iO.

**Comment by pixelzoom** [comment]
Inspecting commits, these should be considered guilty until proven innocent:

@jonathanolson made 2 commits to SimpleDragHandler in 2/2015, both related to transforms. 
@ jonathanolson made a commits to MovableDragHandler in 11/2016 that changed the target node.

If we move on to the introduction of `TandemSimpleDragHandler`, then:

@samreid made 2 commits to MovableDragHandler in 4/2016 and 6/2016 related to PhET-iO.

**Comment by pixelzoom** [comment]
Assigning to @jonathanolson since his commits look the most likely. High priority.

Unassigning myself because I don't have time to work on this.

**Comment by jonathanolson** [comment]
Still fully tracking it down, but I believe my commit https://github.com/phetsims/scenery-phet/commit/8f3aeba8b70e6306a0e2a72de97cbe709ab8f01f exposed a bug in SimpleDragHandler that is very old.

It looks like the provided Trail in SimpleDragHandler is always missing the currentTarget, since it uses:
```js
this.trail = event.trail.subtrailTo( event.currentTarget, true );
```
(where the 'true' excludes the currentTarget from the returned trail).

The flag should be false, but this would potentially break all sorts of things. As we (still) have no automated testing that would determine input handling breaks, I'm inclined to not "fix" that (and to work around the issue in MovableDragHandler).

This is another thing that would be prevented by using a more sane default listener (instead of the hacky SimpleDragHandler).

**Comment by jonathanolson** [comment]
@samreid, can you review the above patch?

This bug is another vote for me to handle https://github.com/phetsims/scenery/issues/131 and https://github.com/phetsims/scenery/issues/218 soon.

**Comment by samreid** [comment]
The proposed workaround looks OK and seems to work properly.  QA will have the final word in our next RC that uses this code :)

**Comment by KatieWoe** [comment]
Saw this on iPhone for https://github.com/phetsims/QA/issues/433 on the later phet-io branch.

**Comment by pixelzoom** [comment]
@KatieWoe does this issue need to be reopened?

**Comment by KatieWoe** [comment]
I don't think so, I checked older releases of the same branch, and this isn't new.  I was just documenting.  But if others disagree It can be reopened.

**Comment by pixelzoom** [comment]
I'm confused.... In https://github.com/phetsims/beers-law-lab/issues/197#issuecomment-272571044, @samreid said "The proposed workaround looks OK and seems to work properly".  But @KatieWoe says this doesn't need to be reopened because "this isn't new".    It may not be new, but it's also not fixed.  Can someone clarify?

**Comment by KatieWoe** [comment]
It looks fixed in published, but it looks like the fix didn't go out to the phet-io branch.

**Comment by pixelzoom** [comment]
@samreid Should the fix be applied to the phet-io branch?

**Comment by pixelzoom** [comment]
... and what is "the phet-io branch".  I see no branch named "phet-io", and 3 branches with "phetio" in their name.

**Comment by KatieWoe** [comment]
https://phet-dev.colorado.edu/html/beers-law-lab/1.6.14-rc.2/beers-law-lab_en-phetio.html?phetioStandalone

**Comment by samreid** [comment]
Our policy is to spend a minimal or no time maintaining these legacy PhET-iO simulations, since we are focusing on their next major release (using modern studio).  Sound OK?

**Comment by pixelzoom** [comment]
OK, let me summarize: It was fixed in the public version. It was not fixed in the legal PhET-iO version because we're not maintaining them.  Therefore it's OK to close this issue.   If I have that wrong, please reopen.
