### ISSUE TITLE
Solute: id for Tandem.createStaticTandem?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#211]
Noticed while commenting on https://github.com/phetsims/phet-io/issues/1247#issuecomment-341138950...

```js
// beers-law-main.js
36 new ConcentrationScreen( tandem.createTandem( 'concentrationScreen' ) ),

//Solute.js:
87 var tandem = Tandem.createStaticTandem( 'concentrationScreen' ).createTandem( 'solutes' );
```

In both cases, `'concentrationScreen'` is the tandem id.   Looking at other uses of `createStaticTandem`, I don't see any other cases like this - where a static id corresponds to a screen's id.  Is the use of `'concentrationScreen'` in both places necessary, or vestigial?

**Comment by samreid** [comment]
There is another case in BeersLawSolution.js:

```js
var tandem = Tandem.createStaticTandem( 'beersLawScreen' ).createTandem( 'solutions' );
```

I added the screen names in these tandems to clarify that `solutes` are only used in `concentrationScreen` and `solutions` are only used in `beersLawScreen`.  Screen names are not used in the other 16 `createStaticTandem` instances because the values are global or apply to all screens.

**Comment by pixelzoom** [comment]
Is there a requirement that ids in Solute.js and BeersLawSolution.js must match those in beers-law-lab-main.js?  If so, then those ids should be factored out.

**Comment by pixelzoom** [comment]
Is there a requirement that ids in Solute.js and BeersLawSolution.js must match those in beers-law-lab-main.js?  If so, then those ids should be factored out.  And documented something like your explanation above.

**Comment by samreid** [comment]
Proposed fix is above, please review.

**Comment by zepumph** [comment]
@pixelzoom, the only difference between a static Tandem and a "normal" one is that a static tandem was designed for places where the `addInstance` call is reached before phet-io has registered listeners and generally prepared/constructed (not in a constructor). Because of this, static tandems are batched, and then all registered at once when phet-io is initialized. Since the main is reached after phet-io is initialized, the "static" tandem will act the same as a "normal" one. 

imo I see this as a very nice way to factor out the screen name tandems and make sure that the actually static instances are handled accordingly. 

The other way to do it is to just factor out the screenTandemName for both places.

**Comment by samreid** [comment]
Please see https://github.com/phetsims/tandem/issues/34 for clarification about static tandems.  Static now means that it is not created from another tandem instance via `tandem.createTandem`.  We are now batching all tandems before listeners are added.  And note that https://github.com/phetsims/tandem/issues/34 is still under review.

**Comment by pixelzoom** [comment]
If `createStaticTandem` in non-static situations like main.js, what is the point in having both  `createTandem` and `createStaticTandem`?   It seems like you could (and do) have 1 function that works in all situations, eliminating the "which do I use?" issue.

**Comment by pixelzoom** [comment]
I'm also unclear on why the tandem ids in Solute.js and BeersLawSolution.js need to match the screen names.  This is the only case in all PhET code where I see this pattern applied.  Why is it needed here?

**Comment by pixelzoom** [comment]
Zoom call with @samreid to discuss:

• Screen tandems were used in Solute.js and BeersLawSolution.js to associate these things with those screens, for API clarity. 
• A general pattern might be to put `ROOT_TANDEM: createRootTandem` is {{REPO}}Constants.js, then use `ROOT_TANDEM` in place of `createStaticTandem`.  The API will be the same for phetio clients, we should decide what's more convenient for PhET developers.
• There is possibility of namespace collision when instrumenting static instances. How to avoid this? What to do if it happens? See https://github.com/phetsims/phet-io/issues/1251
