### ISSUE TITLE
Rename this.tandem to prevent shadowing

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#212]
Please follow the conventions described in https://github.com/phetsims/phet-io/issues/1239

There is one occurrence in PrecipitateParticle and one in ShakerParticle

**Comment by pixelzoom** [comment]
I renamed in PrecipitateParticle, ShakerParticle and TShakerParticle.   

But in PrecipitateParticle:

`this.precipitateParticleTandem = tandem; // Used in TPrecipitateParticle to serialize the tandem name`

and there is no use of the tandem in `TPrecipitateParticle`.  So can this be deleted?

Assigning to @samreid, since he instrumented this sim.

**Comment by samreid** [comment]
Yes, it seems safe to remove.  I tested with phet-io fuzzMouse and didn't see any issues, so I committed the removal.  Back to you @pixelzoom

**Comment by pixelzoom** [comment]
Next question... Why was it necessary for ShakerParticle, but not for PrecipitateParticle?  Seems like their instrumentation would have identical requirements.

**Comment by samreid** [comment]
I couldn't figure out why the tandem was in `TShakerParticle`,  I removed it and the state wrapper still worked properly.  I can't think of a reason that a researcher would need those ids in the state or anything else it might be used for.  Still, to hedge my bets I'd like to double check with @zepumph before committing.

**Comment by zepumph** [comment]
Sounds like an instrument everything policy to me. I'm not sure we need it, but if we do keep it, https://github.com/phetsims/beers-law-lab/commit/4b77ee84913a27c1d2f80a02915db43484085274 has a mistake in it. The toStateObject key `tandem`  was not changed, but fromStateObject is now looking for a `shakerParticleTandem` not a `tandem key.

**Comment by pixelzoom** [comment]
@zepumph does https://github.com/phetsims/beers-law-lab/commit/337433967c3645a7e3ead6cdcab1bd079c05c005 fix the problem that you noted in https://github.com/phetsims/beers-law-lab/issues/212#issuecomment-342317309? 

I certainly don't know whether `shakerParticleTandem` is needed.  Perhaps we should just remove it for symmetry with PrecipitateParticle,  so that they're either both correct or both wrong :)

**Comment by zepumph** [comment]
>@zepumph does 3374339 fix the problem that you noted in #212 (comment)?

I don't think so, I thought it should look like 
![image](https://user-images.githubusercontent.com/6856943/32472078-2c3ff422-c30d-11e7-9c09-7ce0025e8f65.png)

But I agree with you, perhaps we should delete it instead. There are phetioIDs on the instance anyways, so I'm voting delete.

**Comment by pixelzoom** [comment]
OK, so you want to use `shakerParticleTandem` in the state object, as well as in ShakerParticles.  If I interpret that correctly, then there's still a bug in https://github.com/phetsims/beers-law-lab/issues/212#issuecomment-342342630 (preceding comment screenshot).  `stateObject.tandem` should be `stateObject.shakerParticleTandem`, no?

**Comment by pixelzoom** [comment]
I deleted `shakerParticleTandem` from ShakerParticle and TShakerParticle in the previous commit.

@samreid please review.

**Comment by zepumph** [comment]
ARGH, you are very correct, sorry about that.

**Comment by samreid** [comment]
Looks like the tandems are not necessary in the state, I tested and confirmed the state wrapper still behaves nicely.  Closing.
