### ISSUE TITLE
TShaker serialization?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#214]
I don't understand TShaker.  Why are toStateObject and fromStateObject expecting and returning Vector2?   The _location_ of a `Shaker` is a Vector2, not the Shaker itself.

So I was expecting to see something like this in TShaker:

```js
    fromStateObject: function( stateObject ) {
      return {
        location: TVector2.fromStateObject( stateObject.location ),
      };
    },

    toStateObject: function( value ) {
      return {
        location: TVector2.toStateObject( value.locationProperty.get() ),
      };
    },
```

**Comment by samreid** [comment]
Yes, that would be much better, I'll schedule this for implementation.

**Comment by samreid** [comment]
Implemented above, tested in state wrapper.  New state has parts like this:

```json
    "beersLawLab.concentrationScreen.model.shaker": {
        "location": {
            "x": 350,
            "y": 170
        }
    }
```

@pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
Is `TShaker.setValue` still an appropriate function name? Shouldn't it be `setPreviousLocation`?

**Comment by pixelzoom** [comment]
I'm also not clear on why `TShaker` needs this function.

**Comment by samreid** [comment]
PhET-iO provides two types of serialization:
**Data type serialization**  For instance, numbers, strings, Vector2 instances fall into this category.  These values are instantiated by `fromStateObject`.
**Reference type serialization**  For instance, Nodes and Properties.  For instance, if a simulation has one WaterNode that exists for the lifetime of the sim then when we save the state of the sim, we save the dynamic characteristics of the WaterNode (rather than trying to serialize the entire state of the Node).  Then the PhET-iO library calls `setValue()` to update the dynamic characteristics of the WaterNode without dealing with all of Node's many properties.

> Is `TShaker.setValue` still an appropriate function name? Shouldn't it be `setPreviousLocation` I'm also not clear on why `TShaker` needs this function. (Doc might help.)

The static `setValue` methods on TTypes are automatically called by PhET-iO to restore dynamic characteristics of reference-type serialized instances.

I have added these comments to the "how to instrument" docs, and would love to hear your recommendations about how to proceed.

**Comment by pixelzoom** [comment]
Thanks that helps.

Next question about TShaker:

```js
35 this.instance.previousLocation.set( TVector2.fromStateObject( value ) );
51 instance.previousLocation.set( valueFromStateObject.location );
```

Why `instance.previousLocation.set`?  Shaker `previousLocation` is not a Property.

**Comment by samreid** [comment]
`previousLocation` is not an axon Property, but it is an object property (lower case p).  Are you asking why this is using `Vector2.set()` instead of reassigning the value to the new Vector2?  I suspect either would work equally well, unless the sim is somehow relying on reference equality.

**Comment by pixelzoom** [comment]
Ah, `Vector.set`, not `Property.set`.  Got it, thanks for clarifying.  Closing.
