### ISSUE TITLE
application of assertInstanceOf

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#215]
Problems with application of `assertInstanceOf` in beers-law-lab (and possibly other places)

(1) `assertInstanceOf` should be called before calling the supertype constructor.

Example:

```js
  function TShakerParticle( instance, phetioID ) {
    TObject.call( this, instance, phetioID );
    assertInstanceOf( instance, phet.beersLawLab.ShakerParticle );
  }
```

(2) `assertInstanceOf` should be called as the first line of `toStateObject`, to verify that we're serializing the supported type(s).

**Comment by samreid** [comment]
In the preceding commits, I moved the `assertInstanceOf` before the super call in ttypes.

> (2) `assertInstanceOf` should be called as the first line of `toStateObject`, to verify that we're serializing the supported type(s).

Logic in phetio.js already enforces that TWrapperType.toStateObject() is only called on an object wrapped in the corresponding TWrapperType, so introducing new assertion checks in `toStateObject` may be unnecessary.  I suspect/hope the same applies to all other TWrapperType methods, but I haven't verified this.

@zepumph can you comment on (2)?

**Comment by pixelzoom** [comment]
> Logic in phetio.js already enforces that TWrapperType.toStateObject() is only called on an object wrapped in the corresponding TWrapperType

If that's the case, then I would expect to see `assertInstanceOf` or `assertInstanceOfTypes` called somewhere in phetio.js, and that's not the case.  So either it's not checking, or it's not using the same check that was used in the TType constructor - either way, that's a problem.

**Comment by samreid** [comment]
The two calls in phetio.js are safe because they follow the form:

```js
var wrapper = new WrapperType(instance);
// ...
WrapperType.toStateObject(wrapper.instance);
```
The first line would error out if the type didn't match.  However, I broadened my search and found an occurrence of `.toStateObject` in `SimIFrameAPI` that calls `toStateObject` without a corresponding wrapper type or check.  There is another case like this in TArray, so I think we should add the assertions in `toStateObject` and probably any other static TType methods.

@zepumph can you tackle this?

**Comment by zepumph** [comment]
I have an idea, rather than adding this in every subtype, why don't we set a member var on each TType like `validTypes // {Array.<String>}`. Then in TObject we can do the assert call. 

In order for this to work, all toStateObjects will have to call to the parent before adding subType values. We have wanted to do this for other reasons (like general robustness) for a while. This seems like as good a time as any to do so. @samreid do you like the idea?

**Comment by samreid** [comment]
I like the idea but not sure if it will work--depends on whether types can be resolved at the right time.  I tested it out by putting debugger in TNode and it seemed that `phet.scenery.Node` wasn't yet defined.

![image](https://user-images.githubusercontent.com/679486/32468945-a4ee380c-c30d-11e7-9807-33c138070349.png)

**Comment by zepumph** [comment]
:/

**Comment by zepumph** [comment]
I have a bad solution :)
```js
setTimeout( function(){ TNode.validTypes = [phet.scenery.Node]}, ????);
```

Honing it in. . . 

Could it be solved by making validValues a getter, then it would be there by the time it is needed. 
```js

  function TNode( node, phetioID ) {
    assert && assertInstanceOf( node, phet.scenery.Node );
    TObject.call( this, node, phetioID );
  }

  phetioInherit( TObject, 'TNode', TNode, {
        getValidTypes: function(){
               return [ phet.scenery.Node]
        }
        get validTypes() { return getValidTypes() }
}

**Comment by samreid** [comment]
Maybe make it cache & store the result after calling it the first time, so we don't need to allocate arrays every frame?

**Comment by pixelzoom** [comment]
`assertInstance` sounds a lot more straightforward and readable.  Unless there are other places where you need to do type verification.

**Comment by zepumph** [comment]
1. in `toStateObject`
2. in `setValue`
3. in constructor
4. in phetio.js (although slightly redundant, if it was easy to call from here it could be nice to check)

That feels like a lot of duplication, although 1-3 are all in the same file. Even so, aren't we unable to have a constant because of https://github.com/phetsims/beers-law-lab/issues/215#issuecomment-342320366

**Comment by samreid** [comment]
Even if we factored this out, we would need a central way to call the factored out functions (unless we used some sort of decorator pattern in phetioInherit.js, but that sounds too "clever").

What if we try populating the assertion checks everywhere and see if it is too much of a burden?

**Comment by samreid** [comment]
For instance, the proposed change to TNode appears in the preceding master commit.

**Comment by zepumph** [comment]
I think the proposed change above is safe, and appropriate. Feel free to proceed.

**Comment by samreid** [comment]
I'm at about 25/100 of these and wondering if our lives would be better if we moved the instance-based methods (like `clearChildInstances`, `setValue` and `toStateObject`) to instance methods instead of static methods that take an instance.  I guess one contraindication is when using a parameterized type like PropertyIO<NumberIO> then we need to be able to use to/fromStateObject on NumberIO even though there is no NumberIO instance.  But the other ones may be better as instance methods.

**Comment by samreid** [comment]
On the other hand, even for parameterized type or function type parameters, it wouldn't hurt too much to instantiate a wrapper then use it to do toStateObject(), would it?  Or would that create too much garbage?

**Comment by samreid** [comment]
I think `toStateObject` must remain static so it can be called for function types and type parameters, it cannot be wrapped by a temporary wrapper--the temporary wrapper would need a `phetioID`.

**Comment by samreid** [comment]
I added type checks for static methods, @zepumph can you spot check and close?  I'll move https://github.com/phetsims/beers-law-lab/issues/215#issuecomment-345146610 to a new issue.

**Comment by samreid** [comment]
@zepumph if your spot check seems good, please reassign to @pixelzoom to verify.

**Comment by zepumph** [comment]
It looks good to me!

**Comment by zepumph** [comment]
In below commits, @samreid and I added a NullableIO type that will handle cases where the above assertions were failing because of nulls. I also converted many `{min:x, max:y}` to `Range`. https://github.com/phetsims/capacitor-lab-basics/issues/215 is handling a special case for Vector2 and Vector3.

**Comment by pixelzoom** [comment]
I'm not thrilled with the `NullableIO` pattern (see https://github.com/phetsims/phet-io/issues/1275), but this issue can be closed.
