### ISSUE TITLE
User suggestion: Add water

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/beers-law-lab#227]
> Until 1 year ago I worked as a physics teacher in Germany. I often used your extremly fine collection of simulations and got so much benefit for me and my students.
> 
> A visit in a german museum in the town of Stralsund https://www.ozeaneum.de/ showed the following picture (see attachment wasser Oceaneum)
> 
> I tried to visualise this with https://phet.colorado.edu/sims/html/bending-light/latest/bending-light_en.html
> 
> I realised my failure because the sim only visualizes the intensity of reflected/refracted light. (Fresnels formulars)
> 
> Then I tried         https://phet.colorado.edu/en/simulation/concentration
> 
> Unfortunately this didn´t help either because there is no such substance like just plane water where absorption of different colored light is demonstrated.
> 
> My idea is could´nt you add this to this simulation. Then teachers can explain „why appear the seas blue“ and ! why is sunset/sunrise red.
> 
> Interesting is there are 2 phenomena which haven´t that much in common at first sight. Good for student to learn things like that.

**Comment by pixelzoom** [comment]
I'm confused...  Concentration sim doesn't deal with absorption for _any_ solutions, and if you fill the beaker from the faucet, you have water.   Absorption and light color are in the _Beer's Law_ screen of the Beer's Law Lab sim.  Is the user referring to that sim?

**Comment by pixelzoom** [comment]
I talked with @oliver-phet ... The hypothesis is that the user sent the wrong link and is actually referring to the Beer's Law Lab sim.

**Comment by oliver-phet** [comment]
Since the original designer (JC) is no longer here, assigning to @ariel-phet.

**Comment by ariel-phet** [comment]
@pixelzoom @oliver-phet 

First of all, in a sense, water IS available in this sim. For any solution, simply set the value of concentration to 0 mM, and voila, you have water. So, I can see why water would not be included in the combo box, since you cannot change the concentration of pure water, it is always just 0.

This wikipedia article show absorption in the visible spectrum: https://en.wikipedia.org/wiki/Electromagnetic_absorption_by_water#Visible_region

And this picture shows absorbtion coefficients for pure water:

ftp://misclab.umeoce.maine.edu/users/optics/classFTP2015/Labs/Lab2_resources/Pegauetal1997.pdf

With the relevant data in this picture

![water](https://user-images.githubusercontent.com/4051174/40851064-74cbd634-6583-11e8-90e5-925e959c91dc.PNG)

For Blue end of the spectrum the Absorption coefficient is ~ .05, and for the red end of the spectrum it is about 1.

Looking at the "worst case" scenario (as in the most absorption), for 2 cm of water (the max thickness we have in Beer's Law) we get the following

1. For the Blue end of the spectrum, 99.90% transmittance
2. For the Red end of the spectrum 98.02% transmittance

If we wanted to use this information, I think it would be highly problematic. For instance, take the case of drink mix. At 1 mM the transmittance is 99.90% for 780 nm (red light). So if you went from 1 mM to 0 mM (pure water), the transmission would actually decrease, which I don't think is actually correct (and would be confusing). We would need to readjust the model so that as the concentration decreases it approaches the transmittance of pure water for each solution. Likely we would need to take the current data and adjust it for the assumption of pure water having absorption. 

At any rate, there is an assumption being made in the sim that pure water is 100 percent transmission at all visible wavelength, that assumption is in fact incorrect, but not sure it is worth changing.

**Comment by ariel-phet** [comment]
And for reference doing my calculations above with the formula 

I = I_0*e^(-a*x)

**Comment by ariel-phet** [comment]
Assigning back to @pixelzoom for thoughts...but certainly even if we went down this path, no work until after EqEx

**Comment by pixelzoom** [comment]
I read through @ariel-phet's comments in https://github.com/phetsims/beers-law-lab/issues/227#issuecomment-393931693.   If we need to change data for other solutions, that's going to be a much bigger deal.   I'll leave it to the subject-matter experts to decide whether to proceed with this issue.  Back to @ariel-phet to decide who the responsible designer for this sim.

**Comment by ariel-phet** [comment]
I will bring this up at a status or design meeting at some point (probably not until July, since KP is on travel most of June)

**Comment by ariel-phet** [comment]
I asked Amy H. if she would look over this issue, and she said:

> After looking over the issue in GitHub and playing with the sim a bit, I would caution against adding water as a choice to the combo box.  It sounds like this would take a bit of work to make happen and I'm not sure it is that useful pedagogically.  When my students use a spectrophotometer for a lab, the first step is to fill a cuvette with water and calibrate the equipment to read this sample as having zero absorbance. This ensures that any absorbance from water or the cuvette itself is not attributed to the samples that are subsequently tested. The way the sim currently functions is consistent with what students would see after calibrating a spectrophotometer.  If you choose to correct for molar absorptivity of water, then you technically should also correct for any absorptivity from the cuvette as well.
> 
> If you want to report the absorbance/% transmittance readings in the sim as they would appear on a spectrophotometer that hasn't been calibrated, then this change would be appropriate. I'm not sure this buys you much in the way of what users could learn from the simulation and does present the problem of needing to disable/hide the concentration slider if a user selects water from the combo box.

Therefore this seems beyond the scope of this sim, and potentially would be a confusing/damaging change. Closing

**Comment by pixelzoom** [comment]
Reopening. Since this was a user suggestion, should @oliver-phet get back to that user before closing the issue?

**Comment by oliver-phet** [comment]
Thanks, @pixelzoom I replied to the user earlier. Re-closing!
