### ISSUE TITLE
Changing soluteMolesProperty in Studio causes assertion failure

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#266]
Dragging the Studio slider for `beersLawLab.concentrationScreen.model.solution.soluteMolesProperty` crashes with:

```
Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
assert.js:25 Uncaught Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
    at window.assertions.assertFunction (assert.js:25)
    at DataStream.end (dataStream.js:282)
    at PhetioCommandProcessor.phetioEndEvent (PhetioObject.js:407)
    at phetioCommandProcessor.js:121
```

**Comment by pixelzoom** [comment]
soluteAmountProperty was renamed to soluteMolesProperty, for symmetry with soluteGramsProperty.

**Comment by pixelzoom** [comment]
To reproduce:

1. Start the sim in Studio `studio/?sim=beers-law-lab&phetioDebug&phetioElementsDisplay=all&phetioValidation=true`
2. Navigate to `beersLawLab.concentrationScreen.model.solution.soluteMolesProperty` in the Studio tree
3. Drag the Studio slider for  `soluteMolesProperty` to right, then start dragging to the left.  The assertion failure will occur.  And it only seems to occur if you'd dragged a certain amount to the right.

This is another one of those PhET-iO failures where the error message tells me nothing. I am pausing on caught exceptions. I have no idea how to proceed.

@zepumph do you have any suggestions for how to proceed?

**Comment by zepumph** [comment]
Short answer:

This was caused by an assertion error in the sim, thus you can add `?debugger` and get a debugger paused in assert.js on the sim side right when the error happens. Looks like it is occurring here:

https://github.com/phetsims/beers-law-lab/blob/f01f96d373fd2a0847e3fe8357fdde86625a5a13/js/concentration/model/Precipitate.js#L108


Long answer:

The error handling here is less than ideal because PhET-iO captures all errors that occur on the sim side (via a try/catch block) and then sends the back to the  error to the wrapper side. In terms of treating PhET-iO as an API, I think this makes sense. In terms of treating PhET-iO as a product in development, it is a pain in the Butt (capital B). This is especially the case in a team that prefers the loudest, earliest error possible, like we do. To help remedy this a bit, all of our in-house wrappers (like studio) add a global error handler to re-throw any error that it retrieves from the sim. When I reproduce your error, I can see the assertion error stack trace at the top-ish of the stack: 


![image](https://user-images.githubusercontent.com/6856943/111402416-06072700-8680-11eb-8dfc-2cff7ebd3809.png)


The issue is that it is a bit mixed up in phet-io assertions that happen downstream of the problem. Since in this case PhET-iO is a bit too broken in this case to send back the error in order (it drops an event first). 


I hope this helps.

**Comment by pixelzoom** [comment]
No plans to work on this until this sim comes up for republication and/or PhET-iO redesign.  So unassigning.

**Comment by pixelzoom** [comment]
Now that Studio no longer has sliders for numeric values, this cannot be reproduced. And using the "Set Value" button for `soluteMolesProperty` does not fail any assertion, and behaves as expected.  So closing.
