### ISSUE TITLE
`beakerUnits=milliliters` displays incorrect values

### ISSUE THREAD

**Issue by arouinfar** [phetsims/beers-law-lab#295]
Noticed when reviewing #293 

Switching the beaker units to mL swaps out the units string, but doesn't correctly convert the values. The beaker labels should read `500 mL` and `1000 mL`. The behavior is correct in the latest published version, but broken in master (currently reads `½ mL` and `1 mL`).

**Comment by pixelzoom** [comment]
Good catch. This was actually broken in 90be4193 when I added support for dynamic locale.  It's fixed in the above commit.  The screenshots below show the beaker labels when switching the "Beaker units" preference.

@arouinfar feel free to take a peek. But I'm not going to assign this to you to review because it's so simple. Closing.

<img width="203" alt="screenshot_2016" src="https://user-images.githubusercontent.com/3046552/206521977-126867a5-da2c-4241-aefe-0472bdecf921.png">

<img width="219" alt="screenshot_2015" src="https://user-images.githubusercontent.com/3046552/206522000-506792ef-f62a-4303-a491-9f8268d5c0ae.png">
