### ISSUE TITLE
Missing dependency in `concentrationMeterNode`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/beers-law-lab#308]
For #296 

Instances of `labelText` and `valueText` in the Studio tree usually link back to the associated StringProperty or dependencies. This is missing in `*.concentrationScreen.view.concentrationMeterNode.bodyNode.valueText` which seems like an oversight. @pixelzoom can you take a look?

Here's the current tree structure:
<img width="206" alt="image" src="https://user-images.githubusercontent.com/8419308/211935875-3759fb49-b0be-4e5f-9c29-bfae6a47ef79.png">

**Comment by pixelzoom** [comment]
valueText.stringPropery is actually derived from 5 other Properties. Anyone who actually looks at this is likely to say "nevermind", so that's probably why I didn't instrument it.  But it's instrumented now.  Back to @arouinfar for review.

<img width="809" alt="screenshot_2144" src="https://user-images.githubusercontent.com/3046552/211939106-b30b85c3-bb9d-4f9f-95fb-a65b20507232.png">

**Comment by arouinfar** [comment]
> valueText.stringPropery is actually derived from 5 other Properties. Anyone who actually looks at this is likely to say "nevermind", so that's probably why I didn't instrument it.

Oh, that makes sense now. 

> Back to @arouinfar for review.

Looks good in master, thanks!
