### ISSUE TITLE
Should ruler position have bounds?

### ISSUE THREAD

**Issue by stemilymill** [phetsims/beers-law-lab#322]
For https://github.com/phetsims/qa/issues/889

`beersLawLab.beersLawScreen.model.ruler.positionProperty` can be set using setValue to positions far outside dev bounds.

If the window size is manipulated such that the ruler becomes visible, clicking on the ruler will return it to default position.

**Comment by pixelzoom** [comment]
My recommendation is to close this issue as "won't fix".  Over in https://github.com/phetsims/ph-scale/issues/270#issuecomment-1397777747, we concluded that, for movable things that have drag bounds, we're not going to prevent the PhET-iO client from positioning them outside their drag bounds.  It doesn't hurt the sim, and the thing (ruler in this case) will snap into the drag bounds as soon as the user starts dragging it.

@arouinfar if you agree, please close. Otherwise let me know what you'd like to do.

**Comment by arouinfar** [comment]
Completely agree @pixelzoom, closing as wont-fix.
