### ISSUE TITLE
Cuvette snap interval query parameter

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/beers-law-lab#330]
While working on BLL Lab book wrapper in https://github.com/phetsims/phet-io-wrapper-lab-book/issues/13, @samreid and I found that we needed to type in the cuvetteSnapInterval query parameter into the studio URL each time we wanted to save the state config. The Lab Book wrapper requires cuvetteSnapInterval = 0, so if this is not specified in studio, it will fail and the user will need to redo all of their customizations.

This created some awkwardness with using studio to customize the sim, and we feel that it could be improved by integrating this query parameter into PhET-iO and making the default cuvetteSnapInterval = 0 for the PhET brand version.

**Comment by pixelzoom** [comment]
The `cuvetteSnapInterval` query parameter was added in  https://github.com/phetsims/phet-io/issues/568 explicitly for use by UBC in a custom PhET-iO wrapper.  There was no requirement for it to be a Property, and it was made a query parameter because designers said it could be generally useful outside of PhET-iO. 

Since then, I've started adding Properties for all sim-specific query parameters -- not because designers or the PhET-iO Technical Guide tells me to do so, but because of requests like this issue. 

Would you like me to add `snapIntervalProperty` to Cuvette?  Estimate 15 minutes.  Then you can decide whether to patch into 1.7, based on how you're planning to deliver https://github.com/phetsims/phet-io-wrapper-lab-book/issues/13.

**Comment by pixelzoom** [comment]
I went ahead and did this. In the above commits, I added PhET-iO element `cuvette.snapIntervalProperty`, whose initial value is set via `?cuvetteSnapInterval`.  

Here's the implementation in Cuvette.ts. Note that it's `phetioFeatured: true`, because we typically feature Properties that are associated with query parameters. 

```
    this.snapIntervalProperty = new NumberProperty( BLLQueryParameters.cuvetteSnapInterval, {
      units: 'cm',
      range: BLLConstants.CUVETTE_SNAP_INTERVAL_RANGE,
      tandem: options.tandem.createTandem( 'snapIntervalProperty' ),
      phetioFeatured: true, // Properties associated with query parameters are typically featured
      phetioDocumentation: 'When dragging the cuvette, it\'s width will snap to this interval when the drag ends. Use 0 for no snapping.'
    } );
```

This did result in a PhET-iO API change, so beers-law-lab-phet-io-api.json was also updated. 

Back to @matthew-blackman to review.  https://github.com/phetsims/phet-io-wrapper-lab-book/issues/13#issuecomment-1462641060 sounds like you'll also want to cherry-pick these commits into beers-law-lab 1.7.

**Comment by matthew-blackman** [comment]
This API change makes sense and I think it's an improvement, but the Lab Book wrapper work has concluded and the client was delivered a working zip. I don't see the need for cherry picking here unless there are other reasons not related to the Lab Book wrapper. Removing the ready-for-review label for now.

**Comment by pixelzoom** [comment]
Great, thanks for the clarification @matthew-blackman.  I think we can close this issue, and reopen (or create a new issue) if there are additional client needs.
