### ISSUE TITLE
use PropertySet where appropriate

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#91]
This sim doesn't use PropertySet, there are places where it would be appropriate.

Related to #90 (use DerivedPropertySet where appropriate).

**Comment by pixelzoom** [comment]
I decided not to do this. Most model and view types have 1 or 2 Properties.  And the syntax for specifying together componentID is quite a bit uglier for PropertySet.

**Comment by samreid** [comment]
Since https://github.com/phetsims/together/issues/49 has been resolved by https://github.com/phetsims/together/issues/72, an uglier syntax for PropertySet is no longer a valid reason for avoiding this work.  However, perhaps "most model and view types have 1 or 2 Properties" may still be a sufficient reason to leave this issue closed.  Up to @pixelzoom to decide, I'm fine either way.

**Comment by pixelzoom** [comment]
The majority of model elements have 1 axon.Property.  Dropper is the outlier, with 5 axon.Properties.  I see no benefits to switching to PropertySet, so closing.
